apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s4llfbx0f-python
  janus-idp.io/tekton: s4llfbx0f-python
  backstage.io/kubernetes-id: s4llfbx0f-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: s4llfbx0f-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
